### ISSUE TITLE
Fails to produce output on silent videos

### ISSUE THREAD

**Issue by computer2467** [YTP-Plus/YTPPlusPlus#7]
After a couple hours of poking around with this (since a lot of my renders were failing and there wasn't really a console to check for fast answers) I have figured out that I had two silent clips in my source pool and it caused the final concat command to throw with `Stream specifier ':a:0' in filtergraph description [0:v:0][0:a:0][1:v:0][1:a:0][2:v:0][2:a:0][3:v:0][3:a:0][4:v:0][4:a:0][5:v:0][5:a:0][6:v:0][6:a:0][7:v:0][7:a:0][8:v:0][8:a:0][9:v:0][9:a:0][10:v:0][10:a:0][11:v:0][11:a:0][12:v:0][12:a:0][13:v:0][13:a:0][1
4:v:0][14:a:0][15:v:0][15:a:0][16:v:0][16:a:0][17:v:0][17:a:0][18:v:0][18:a:0][19:v:0][19:a:0][20:v:0][20:a:0]concat=n=21:v=1:a=1[outv][outa] matches no streams.` (using default settings, so 20 clips + outro) None of the individual effects shows any sign of throwing, which is why I gave up here due to my limited knowledge of ffmpeg. [One of the throwing clips](https://filebin.net/na38aogdc3t7nuu0/942442e05f1abd6e140a26192dc16aa3.mp4?t=o6yc0q26) information is listed below.
```bash
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\942442e05f1abd6e140a26192dc16aa3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:07.15, start: 0.000000, bitrate: 25 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 128x58, 21 kb/s, 24.49 fps, 24.49 tbr, 24492 tbn, 48.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

**Comment by TeamPopplio** [comment]
This is a known issue due to the FFMPEG commands not accounting for anything regarding silent clips. I've always asked anyone who had encountered the ":a:0" issue if they had any silent clips on the discord but I haven't gotten around to fixing it. I'll make an attempt to do so by using FFProbe to see if the clip is silent first whenever possible.

Alongside that, there is a console inside of the view menu for debugging purposes. Thanks for bringing this to my attention!

**Comment by TeamPopplio** [comment]
Merging to #11.
